version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

volumes:
  wallabag-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/wallabag/data
  wallabag-media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/wallabag/media

services:
  wallabag-db:
    container_name: wallabag-db
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    volumes:
      - wallabag-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  wallabag-redis:
    container_name: wallabag-redis
    image: redis:alpine
    security_opt:
      - no-new-privileges:true
    networks: 
      - internal
    volumes:
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    labels:
      - "traefik.enable=false"
    restart: unless-stopped

  wallabag-app:
    container_name: wallabag-app
    image: wallabag/wallabag:latest
    depends_on:
      - wallabag-db
      - wallabag-redis
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=wallabag-db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=${DB_USER_PASS}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=${SMTP_EMAIL}
      - SYMFONY__ENV__DOMAIN_NAME=https://${SUBDOMAIN}.${DOMAIN}
      - SYMFONY__ENV__REDIS_HOST=wallabag-redis
    volumes:
      - wallabag-media:/var/www/wallabag/web/assets/images
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallabag.entrypoints=http"
      - "traefik.http.routers.wallabag.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.wallabag.middlewares=secured@file"
      - "traefik.http.routers.wallabag-secure.entrypoints=https"
      - "traefik.http.routers.wallabag-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.wallabag-secure.tls=true"
      - "traefik.http.routers.wallabag-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.wallabag-secure.service=wallabag"
      - "traefik.http.services.wallabag.loadbalancer.server.port=80"
    networks:
      - proxy
      - internal
    # Used for SSH tunnel proxy
    ports:
      - 4002:80
    restart: unless-stopped