version: '3'

volumes:
  ha-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/config

  ha-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/database      

  ha-zigbee2mqtt-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/zigbee2mqtt/data

  ha-mosquitto-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/mosquitto/config

  ha-mosquitto-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/mosquitto/data

services:
  ha-mariadb:
    container_name: ha-mariadb
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=homeassistant
      - MYSQL_USER=homeassistant
      - MYSQL_PASSWORD=${DB_USER_PASS}
      - TZ=Europe/Amsterdam
    volumes:
      - ha-mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  ha-mqtt:
    container_name: ha-mqtt
    image: eclipse-mosquitto:latest
    security_opt:
      - no-new-privileges:true
    volumes:
      - ha-mosquitto-config:/mosquitto/config
      - ha-mosquitto-data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1883:1883"
    environment:
      - TZ=Europe/Amsterdam
    labels:
      - "traefik.enable=false"
    restart: unless-stopped

  ha-zigbee2mqtt:
    container_name: ha-zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    security_opt:
      - no-new-privileges:true
    depends_on:
      - ha-mqtt
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ha-zigbee2mqtt-data:/app/data
      - /etc/localtime:/etc/localtime:ro
    # Map local /dev mountpoint to docker
    devices:
      - ${ZIGBEE_DEVICE_MOUNT}:/dev/ttyZigbee
    labels:
      - "traefik.enable=false"
    ports:
      - "8099:8099"
    restart: unless-stopped

  ha-app:
    container_name: ha-app
    image: homeassistant/home-assistant:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Amsterdam
    # Map local /dev mountpoint to docker
    devices:
      - ${RFX_DEVICE_MOUNT}:/dev/ttyRFXtrx
    volumes:
      - ha-config:/config
      - /sys/class/thermal:/sys/class/thermal
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    depends_on:
      - ha-mariadb
      - ha-mqtt
      - ha-zigbee2mqtt
    network_mode: host
    restart: unless-stopped