version: '3.3'

volumes:
  jackett-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/jackett/config
  jackett-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/jackett/downloads

services:
  jackett:
    container_name: jackett
    image: ghcr.io/linuxserver/jackett:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:expressvpn
    restart: unless-stopped
