name: qbittorrent

volumes:
  qbittorrent-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/qbittorrent/config
  qbittorrent-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/downloads

services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=${WEBUI_PORT}
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - qbittorrent-downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    network_mode: "container:gluetun"
    # Ports exposed on the Gluetun side instead
    # ports:
    #   - 8486:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    restart: unless-stopped
