version: '3'

networks:
  proxy:
    external: 
      name: proxy

volumes:
  ampache-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/ampache/config
  ampache-log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/ampache/log
  ampache-media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/ampache/media
  ampache-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/ampache/database
  ampache-sites-enabled:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/ampache/sites-enabled

services:
  ampache:
    image: ampache/ampache:latest
    container_name: ampache
    security_opt:
      - no-new-privileges:true
    volumes:
      - ampache-config:/var/www/config
      - ampache-log:/var/log/ampache
      - ampache-media:/media
      - ampache-database:/var/lib/mysql
      - ampache-sites-enabled:/etc/apache2/sites-enabled
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ampache-app.entrypoints=http"
      - "traefik.http.routers.ampache-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.ampache-app.middlewares=https-only@file"
      - "traefik.http.routers.ampache-app-secure.entrypoints=https"
      - "traefik.http.routers.ampache-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.ampache-app-secure.tls=true"
      - "traefik.http.routers.ampache-app-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.ampache-app-secure.service=ampache-app"
      - "traefik.http.services.ampache-app.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped