name: audiobookshelf

volumes:
  audiobookshelf-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/audiobookshelf/config
  audiobookshelf-metadata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/audiobookshelf/metadata
  audiobookshelf-audiobooks-dir:
    driver: local
    driver_opts:
      type: ${MEDIA_DRIVER_OPT_TYPE}
      o: ${MEDIA_DRIVER_OPT_O}
      device: ${AUDIOBOOKS_PATH}
  audiobookshelf-ebooks-dir:
    driver: local
    driver_opts:
      type: ${MEDIA_DRIVER_OPT_TYPE}
      o: ${MEDIA_DRIVER_OPT_O}
      device: ${EBOOKS_PATH}
  audiobookshelf-podcasts-dir:
    driver: local
    driver_opts:
      type: ${MEDIA_DRIVER_OPT_TYPE}
      o: ${MEDIA_DRIVER_OPT_O}
      device: ${PODCASTS_PATH}

services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    security_opt:
      - no-new-privileges:true
    volumes:
      - audiobookshelf-config:/config
      - audiobookshelf-metadata:/metadata
      - audiobookshelf-audiobooks-dir:/audiobooks
      - audiobookshelf-ebooks-dir:/ebooks
      - audiobookshelf-podcasts-dir:/podcasts
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TIMEZONE}
    ports:
      - 13378:80
    restart: unless-stopped
