version: "3.7"

networks:
  proxy:
    external:
      name: proxy

volumes:
  nodered-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/node-red/data
  # nodered-download-dir:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${STORAGE_ROOT}/downloads/complete
      

services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest-minimal
    restart: always
    user: root
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - nodered-data:/data
      - /etc/localtime:/etc/localtime:ro
      # - nodered-download-dir:/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.entrypoints=http"
      - "traefik.http.routers.nodered.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.nodered.middlewares=https-only@file"
      - "traefik.http.routers.nodered-secure.entrypoints=https"
      - "traefik.http.routers.nodered-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.nodered-secure.tls=true"
      - "traefik.http.routers.nodered-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.nodered-secure.service=nodered"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
    networks:
      - proxy