version: "2.1"

volumes:
  transmission-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/transmission/config
  transmission-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/downloads
  transmission-watchdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/transmission/watch

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - transmission-config:/config
      - transmission-downloads:/downloads
      - transmission-watchdir:/watch
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:expressvpn
    restart: unless-stopped