name: slskd

networks:
  proxy:
    name: proxy
    external: true

volumes:
  slskd-app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/slskd/app
  slskd-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/slskd/data

services:
  slskd-app:
    container_name: slskd-app
    image: slskd/slskd
    security_opt:
      - no-new-privileges:true
    ports:
      - "50300:50300"
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TIMEZONE}
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - slskd-app:/app
      - slskd-data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.slskd-app-secure.entrypoints=websecure
      - traefik.http.routers.slskd-app-secure.rule=Host(`${SUBDOMAIN:+${SUBDOMAIN}.}${DOMAIN}`)
      - traefik.http.routers.slskd-app-secure.tls=true
      - traefik.http.routers.slskd-app-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.slskd-app-secure.service=slskd-app
      - traefik.http.routers.slskd-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.slskd-app.loadbalancer.server.port=5030
    restart: unless-stopped
